services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    env_file: .env
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 127.0.0.1:1888:1888 # pprof extension
      - 127.0.0.1:8888:8888 # Prometheus metrics exposed by the Collector
      - 127.0.0.1:8889:8889 # Prometheus exporter metrics
      - 127.0.0.1:13133:13133 # health_check extension
      - 127.0.0.1:4317:4317 # OTLP gRPC receiver
      - 127.0.0.1:4318:4318 # OTLP http receiver
      - 127.0.0.1:55679:55679 # zpages extension
